<a href="https://colab.research.google.com/github/young0228/Keras/blob/main/Artificial_Intelligence_lesson01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

Python 3.7.12


In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
                                               
print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


 여기서 def는 함수 선언해주는 함수

 quicksort는 함수명, arr는 함수의 입력인자

In [ ]:
x=3
print(x, type(x))

3 <class 'int'>


In [ ]:
print(x+1)    #Addition
print(x-1)    #Subtraction
print(x*2)    #Multipliaction
print(x ** 2) #Exponentiation

4
2
6
9


In [ ]:
x +=1
print(x)
x *=2
print(x)

4
8


x +=1은 x에 1 더하는 것

In [ ]:
y=2.5
print(type(y))
print(y, y+1, y*2, y**2)

<class 'float'>
2.5 3.5 5.0 6.25


.을 입력해주지 않으면 실수가 아닌 정수로 인식해 계산해버릴 수 있으니까 조심하기

In [ ]:
t, f=True, False
print(type(t))

<class 'bool'>


In [ ]:
print(t and f) #Logical AND; 둘다 true여야 true가 나옴
print(t or f)  #Logical OR;  둘 중에 하나가 true면 true 나옴
print(not t)   #Logical NOT;
print(t != f)  #LOgical XOR; 

False
True
False
True


In [ ]:
hello='hello' #String literals can use single quotes
world="world" # or double quotes; it does not atter
print(hello, len(hello))

hello 5


In [ ]:
hw=hello+' '+world # String concatenation
print(hw)

hello world


In [ ]:
hw12='{} {} {}'.format(hello, world, 12) #String formatting
print(hw12)

hello world 12


In [ ]:
s="hello"
print(s.capitalize())   #Capitalize a string
print(s.upper())        #Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      #Right-justify a string, padding with spaces
print(s.center(7))      #Center a string padding with spaces
print(s.replace('l','(ell)')) #Replace all instances of one substring with another
print('   world'.strip()) #Strip leading and trailing whitespace

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [ ]:
xs= [3,1,2] #Create a list
print(xs, xs[2])
print(xs[-1]) #Negative indices count from the end of the list; prints "2"
print(xs[0])
print(xs[1])

[3, 1, 2] 2
2
3
1


숫자 0부터 시작함

In [ ]:
xs[2] = 'foo' #Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [ ]:
xs.append('bar')  #Add a new element to the end of the list
print(xs)

[3, 1, 'foo', 'bar']


In [ ]:
x=xs.pop() #Remove and return the last element of the list
print(x, xs)

1 [3]


실행해볼때마다 맨 뒤의 애들이 지워짐

In [ ]:
nums = list(range(5))   #Range is a built-in function that creates a list of integers
print(nums)             #Prints "[0,1,2,3,4]"
print(nums[2:4])        #Get a slice from index 2 to 4 (exclusive); prints "[2,3]"
print(nums[2:])         #Get a slice from index 2 to the end: prints "[2,3,4]"
print(nums[:2])         #Get a slice from the start to index 2 (exclusive); prints "[0,1]"
print(nums[:])          #Get a slice of the whole list; prints "[0,1,2,3,4]"
print(nums[:-1])        #Slice indices can be negative; prints '[0,1,2,3]
nums[2:4] = [8,9]       #Assign a new sublist to a slice
print(nums)             #Print "[0,1,8,9,4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


nums[]에서 중요한 것은 앞에 있는 것 포함, 뒤에 있는 건 미포함이라는 것

In [ ]:
animals = ['cat','dog','monkey']
for animal in animals:
    print(animal)

for i in range(10):
    print(i)

cat
dog
monkey
0
1
2
3
4
5
6
7
8
9


In [ ]:
animals = ['cat','dog','monkey']
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#1: cat
#2: dog
#3: monkey


idx + 1을 한거는 0부터 시작이기 때문에 편하게 보기 위해서 1을 더해준 것임

In [ ]:
nums = [0,1,2,3,4]
squares = []
for x in nums:
    squares.append(x**2)
print(squares)

[0, 1, 4, 9, 16]


In [ ]:
nums = [0,1,2,3,4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


In [ ]:
nums = [0,1,2,3,4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


x가 2로 나눴을 때 0이라는 것은 짝수라는 거니까 짝수인 애들만 프린트해달라는 뜻

In [ ]:
d = {'cat': 'cute','dog': 'furry'} # Create a new dictionary with same data
print(d['cat'])     #Get an entry from a dictionary
print('cat' in d)   #Check if a dictionary has a given key

cute
True


In [ ]:
d['fish'] = 'wet'   #Set an entry in a dictonary
print(d['fish'])    #Prints "wet"

wet


In [ ]:
print(d['monkey'])

KeyError: ignored

In [ ]:
print(d.get('monkey', 'N/A'))   #값이 없으면 대체
print(d.get('fish', 'N/A'))

N/A
wet


In [ ]:
del d['fish']                 #Delete
print(d.get('fish', 'N/A'))

N/A


In [ ]:
d = {'person': 2, 'cat':4, 'spider':8}
for animals, legs in d.items():
    print('A {} has {} legs'.format(animals, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [ ]:
nums = [0,1,2,3,4]
even_num_to_square =  {x: x ** 2 for x in nums if x % 2 ==0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


[] List {} Dictionary

In [ ]:
animals = {'cat','dog'}
print('cat' in animals)
print('fish' in animals)

True
False


In [ ]:
animals.add('fish')
print('fish' in animals)
print(len(animals))   #number of elements in a set

True
3


In [ ]:
animals.add('cat')
print(len(animals))
animals.remove('cat')
print(len(animals))

3
2


이미 있는 것은 추가해도 추가가 되지 않음 그래서 추가해봤자 똑같이 3개인데 제거하면 cat이 사라져서 2개가 됨

In [ ]:
animals = {'cat','dog','fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx+1, animal))

List는 내가 입력한대로 순서가 들어가는데 Set은 규정대로 정함.

In [ ]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})
int(5.9)

{0, 1, 2, 3, 4, 5}


5

sqrt가 제곱근 함수라는데 그래서 25의 제곱근인 5까지 들어있음, 그리고 int쓰면 버림인가봐

In [ ]:
d = {(x, x+1): x for x in range(10)} #Create dictionary keys with tuple keys
t = (5,6)  #Create a tupe
print(type(t))
print(d)
print(d[t])
print(d[(1,2)])

<class 'tuple'>
{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
5
1


In [ ]:
t[0]=1

TypeError: ignored

튜플은 한 번 만들고 나면 Assignment가 되지 않음

---
한 번 만들어지면 변경이 안됨


In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('HELLO, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

HELLO, Bob!
HELLO, FRED


In [ ]:
class Greeter:

  # Constructor
  def __init__(self, name):
    self.name = name #Create an instance variable
  
  # Instance Method
  def greet(self, loud=False):
    if loud:
      print('HELLO, {}'.format(self.name.upper()))
    else:
      print('Hello {}!'.format(self.name))

g = Greeter('Fred') #Construct an insatance of the Greeter
g.greet()           #Call an instance method
g.greet(loud=True)  #Call an instance method

Hello Fred!
HELLO, FRED


In [ ]:
import numpy as np

과학적 계산을 위한 패키지 numpy를 불러오기 위해 import 사용, as로 이름 바꿔줌

class가 함수와 데이터가 모두 있는건데 self.name = name이라고 하면 ,내가 정의하고 있는 클래스 안에 있는 변수라는 뜻

In [ ]:
a = np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [ ]:
a = np.zeros((2,2))  
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2))
print(e)

[[0.95178489 0.23075513]
 [0.19666069 0.78806168]]


In [ ]:
import numpy as np

a= np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

b=a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [ ]:
print(a[0,1])
b[0,0]=77
print(a[0,1])

77
77


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
row_r1= a[1, :]
row_r2= a[1:2, :]
row_r3= a[[1], :]
print(row_r2, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r2, row_r3.shape)

[[5 6 7 8]] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2], [0,1,0]])
print(np.array([a[0,0], a[1,1], a[2,0]]))

[1 4 5]
[1 4 5]


In [ ]:
print(a[[0,0],[1,1]])
print(np.array([a[0,1], a[0,1]]))

[2 2]
[2 2]
